# Generated by Django 3.2 on 2022-02-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('linea_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('linea_nombre', models.CharField(max_length=100, verbose_name='nombre de linea')),
                ('linea_estado', models.CharField(max_length=10, verbose_name='estado linea')),
            ],
        ),
    ]
