# Generated by Django 3.2 on 2022-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('marca_nombre', models.CharField(max_length=100, verbose_name='nombre de marca')),
                ('marca_estado', models.CharField(max_length=10, verbose_name='estado marca')),
            ],
        ),
    ]
