# Generated by Django 3.2 on 2022-02-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('um_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('um_descripcion', models.CharField(max_length=100, verbose_name='desscripcion de la unidad medida')),
                ('um_estado', models.CharField(max_length=10, verbose_name='estado unidad medida')),
            ],
        ),
    ]
