# Generated by Django 3.2 on 2022-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_unidadmedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('moneda_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('moneda_descripcion', models.CharField(max_length=100, verbose_name='desscripcion de la moneda')),
                ('moneda_estado', models.CharField(max_length=10, verbose_name='estado moneda')),
            ],
        ),
    ]
