# Generated by Django 3.2 on 2022-02-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_imagen',
            field=models.CharField(default='', max_length=1000, verbose_name='imagen url producto'),
        ),
    ]
