# Generated by Django 3.2 on 2022-02-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.CharField(default='', max_length=8000, verbose_name='imagen url producto'),
        ),
    ]
