# Generated by Django 3.2 on 2022-02-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_producto_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clientes_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('clientes_numdoc', models.CharField(max_length=100, verbose_name=' cliente_numdoc')),
                ('clientes_nombres', models.CharField(max_length=50, verbose_name='cliente_nombres')),
                ('clientes_apellidos', models.CharField(max_length=50, verbose_name='cliente_apellidos')),
                ('clientes_razonsocial', models.CharField(max_length=100, verbose_name='cliente_razonsocial')),
                ('clientes_telefono', models.CharField(max_length=20, verbose_name='cliente_telefono')),
                ('clientes_direccion', models.CharField(max_length=100, verbose_name='cliente_direccion')),
                ('clientes_estado', models.CharField(max_length=10, verbose_name='cliente_estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pedido subtotal')),
                ('pedido_igv', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pedido igv')),
                ('pedido_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pedido total')),
                ('pedido_estado', models.CharField(max_length=10, verbose_name='estado pedido')),
                ('clientes_codigo', models.ForeignKey(db_column='clientes_codigo', on_delete=django.db.models.deletion.RESTRICT, related_name='Pedido', to='api.clientes', verbose_name='Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('tipodoc_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipodoc_descripcion', models.CharField(max_length=100, verbose_name='tipodoc_descripcion')),
                ('tipodoc_estado', models.CharField(max_length=10, verbose_name='tipodoc_estado')),
            ],
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('ubigeo_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ubigeo_departamento', models.CharField(max_length=50, verbose_name='ubigeo_departamento')),
                ('ubigeo_provincia', models.CharField(max_length=50, verbose_name='ubigeo_provincia')),
                ('ubigeo_distrito', models.CharField(max_length=50, verbose_name='ubigeo_distrito')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('pedidodetalle_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('pedidodetalle_precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pedido detalle precio')),
                ('pedidodetalle_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pedido detalle cantidad')),
                ('pedidodetalle_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pedido detalle sub total')),
                ('pedidodetalle_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='pedido detalle total')),
                ('pedidodetalle_estado', models.CharField(max_length=10, verbose_name='estado pedido')),
                ('pedido_codigo', models.ForeignKey(db_column='pedido_codigo', on_delete=django.db.models.deletion.RESTRICT, related_name='PedidoDetalle', to='api.pedido', verbose_name='Pedido')),
                ('producto_codigo', models.ForeignKey(db_column='producto_codigo', on_delete=django.db.models.deletion.RESTRICT, related_name='PedidoDetalle', to='api.producto', verbose_name='Producto')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipodoc_codigo',
            field=models.ForeignKey(db_column='tipodoc_codigo', on_delete=django.db.models.deletion.RESTRICT, related_name='Clientes', to='api.tipo_documento', verbose_name='Tipo_documento'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ubigeo_codigo',
            field=models.ForeignKey(db_column='ubigeo_codigo', on_delete=django.db.models.deletion.RESTRICT, related_name='Clientes', to='api.ubigeo', verbose_name='Ubigeo'),
        ),
    ]
