# Generated by Django 3.2 on 2022-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220206_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='pedidodetalle_estado',
            field=models.CharField(max_length=10, verbose_name='estado pedido detalle'),
        ),
    ]
